fix java.lang.LinkageError due to cache invalidation bug
cbtHasChanged does never change across one run. However
classLoaderRecursion removes the corresponding classloader if
needsUpdate is true. It is called multiple times meaning it removes
and re-creates the classloader on every call leading to potentially
multiple conflicting cbt classloaders. needsUpdate should never be
returning true more than ones across a single run. Otherwise it can
lead to this error:

java.lang.LinkageError: loader constraint violation in interface itable initialization: when resolving method "Build.lib()Lcbt/Lib;" the class loader (instance of cbt/URLClassLoader) of the current class, Build, and the class loader (instance of cbt/URLClassLoader) for interface cbt/BaseBuild have different Class objects for the type cbt/Lib used in the signature